### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by asymmetric** [ulif/diceware#46]
Hi, I'm trying to [create a `dicewre` package](https://github.com/NixOS/nixpkgs/pull/35569) for NixOS, and it would be great if I could simply pull  the latest release. At the moment, there are [bugs](https://github.com/ulif/diceware/commit/5f37b234aea5252863f604ed1227608e1d5536b4)/[problems](https://github.com/ulif/diceware/commit/86379bf49ade2b486071d6d330515f01ecb06ab4#diff-059bf8ff265c34c564c60270290d636f) in the tests on the latest release.

Thanks!

**Comment by ulif** [comment]
You're right. There should be a new release until tomorrow evening.

Thanks for your packaging, @asymmetric! Please tell, if you need any other help/support!

**Comment by drebs** [comment]
For the record, in the debian package, I had to [patch 3 things for 0.9.3](the year in the manual page and version string), otherwise auto testing fails during package build.

**Comment by ulif** [comment]
Thanks @drebs for this additition. Looks like the "year in docs"-tests are all broken. They fail automatically after a year has passed, which is not correct.

I just changed the test setup so that these tests are not run automatically anymore, except if you run `tox` or if you require the "packaging" tests to run as well. Would that help for now? (in the long run, we need proper tests, of course)

**Comment by asymmetric** [comment]
@ulif works for me.

**Comment by ulif** [comment]
v0.9.4 is out. Thank you @asymmetric and @drebs for hinting!

I hope this (and upcoming) releases will not raise any date problems on Jan, 1st 2019.
The real problem, however is yet to be fixed and will be monitored in #47.
